### ISSUE TITLE
Receiving a local discovery message causes an array out of bounds exception

### ISSUE THREAD

**Issue by tavalin** [tavalin/s20-sdk#7]
```
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 35
    at com.github.tavalin.s20.commands.AbstractCommandHandler.updatePowerState(AbstractCommandHandler.java:155)
    at com.github.tavalin.s20.commands.LocalDiscoveryHandler.handleIncoming(LocalDiscoveryHandler.java:54)
    at com.github.tavalin.s20.network.TransportManager.processMessage(TransportManager.java:267)
    at com.github.tavalin.s20.network.TransportManager.packetReceived(TransportManager.java:251)
    at com.github.tavalin.s20.network.DatagramSocketReader.notifyListeners(DatagramSocketReader.java:112)
    at com.github.tavalin.s20.network.DatagramSocketReader.run(DatagramSocketReader.java:87)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by tavalin** [comment]
Fixed in https://github.com/tavalin/s20-sdk/pull/8
